### ISSUE TITLE
Create a 750-1000 word document

### ISSUE THREAD

**Issue by anuj672** [bhaveshittadwar/csc-510-se-group-49#8]

**Comment by bhaveshittadwar** [comment]
Hi @itsJash , Please take a look at this and let me know if it looks good?

# What was hard about this process?
### 1. Environment Setup
- Setup for all devices was not mentioned in the docs. The project's dependencies and tools might need separate configurations for different Operating systems, versions, or types (for example, Mac Intel, Mac M1(/2) chips). To run on a Mac M1 we configured dos2unix.
### 2. Hardcoded & expired API tokens
- The bash script present in the code had a hardcoded API Token (ref: https://github.com/prithvish-doshi-17/MyDollarBot-BOTGo/blob/main/user.properties) This threw an error. As a result, the test cases were failing.
### 3. Test-Case mismatch
One of the test cases was specified but the mock data for it was missing leading to failed test cases. (Ref: https://github.com/prithvish-doshi-17/MyDollarBot-BOTGo/blob/main/test/test_helper.py#L176)
### 4. Bot claimed to be deployed, but couldn't find
- The docs mention how the bot is deployed using GCP (reference: https://github.com/prithvish-doshi-17/MyDollarBot-BOTGo#whats-new-from-phase-2-to-phase-3) but wasn't found on telegram.
### 5. A few commands mentioned were not running
- The command `python run -m pytest test/` was either a deprecated command or an incorrect one
# How that pain could have been avoided
### 1. Comprehensive Documentation
- Ensure that the project's documentation includes detailed instructions for setting up the development environment on various platforms (Windows, macOS, Linux) and architecture types (e.g., Mac M1). This documentation should provide step-by-step guidance, including any platform-specific considerations.
### 2. Versions
- There were no specific versions for any dependencies in the requirements.txt file. Just mentioning the versions would help save a lot of setup time and would eliminate guesswork about which version would run that project.
### 3. Overview of test cases
- A comprehensive overview of test cases in the docs would have helped us navigate through the errors and test failures with more certainty.
### 4. Description of how GCP is set up for the bot
- As mentioned earlier we were not able to find the deployed bot on Telegram and a detailed guide on how the GCP environment was set up could have helped us demystify why the deployed service was no longer active.
### 5. Storing tokens in a better way
Sensitive information such as API Tokens, keys, and passwords should never be pushed into the code. Making use of `.env` file and documenting how to create a user and generate an API token would've been clearer and more secure.
# The practices we are committing to perform in the project 2

 Also, we could consider containerization to avoid device-specific setup complications using Docker. This provides easier reproducible setups.
 
###  1. Comprehensive Documentation
 There were a lot of places where just having clearer documentation could have saved us a lot of time and effort. For instance: OS-specific steps for setting up would have quickly helped us set up the project on different Mac and Windows OS. Also, a better description of what each unit test checks would have helped us understand better the intent of writing that test case. For GCP, if we could find a doc explaining how it was set up, we could figure out easily why it's no longer available on the specified channel. We will improve and articulate any and every detail that we can include in the documentation. 
### 2. Versions
- The requirements.txt file doesn't mention the version for any of the dependencies. Packages are always evolving and may not be forward-compatible. Just mentioning the versions used while creating the project eliminates any kind of uncertainty. We will ascertain all the versions for the project.
### 3. Setting up environment variables
We'll all the hardcoded sensitive information such as API tokens or keys etc and write a doc on how to set them up locally with an example.
### 4. Dockerization
To truly make this project platform independent and free from setup effort and guesswork we aim to containerize this application so that it can be setup anywhere quickly.

**Comment by itsJash** [comment]
I have updated the writeup and pushing it.

**Comment by bhaveshittadwar** [comment]
Great, thanks
